.Dd March 8th, 2025
.Dt cate 1
.Os
.Sh NAME
.Nm cate
.Nd The easy C/C++ build system
.Sh SYNOPSIS
.Nm cate
.Op Fl hlitvynDdSfv
.Op Ar option?
.Op Ar catefile ...
.Sh DESCRIPTION
.Nm Cate
is an easy build system for C/C++ that makes the developer's life easier.
This introduction is for the casual user, if you'd like to learn how to write a
catefile, refer to the "catering" man page.
.Pp
Here are the flags:
.Pp
.Bl -tag -width ".Cm activate"
.It Fl h/?
Lists the help screen.
.It Fl l
Lists all catefiles available.
.It Fl y
Always answers
.Nm yes
to install commands.
.It Fl n
Always answers
.Nm no
to install commands.
.It Fl S
Smolizes even if not set in file.
.It Fl f
Forcefully rebuilds the file's things.
.It Fl v
Shows version
.It Fl t Ar count
Sets the maximum thread count. Unneeded because cate automatically gets it.
.It Fl i Ar name
Inits a new C project with cate. Refer to the "catering" man page for info.
.El
.Sh EXAMPLES
Most of the time you can just run
.Dl "$ cate"
And it will work!
.Pp
The following lists all available catefiles
.Dl $ cate -l
.Pp
To select a catefile, just name it
.Dl $ cate debug
You can use multiple in a single command
.Dl $ cate game modmenu