.TH cate 1-cli 2022-10-13 

.SH Description
.B Cate
is a simple build system for C/C++

.SH Notes:
Cate automatically gets thread-count, you do not need to set it with the
.B
-tN
flag 

.SH CLI usage
.B cate
<flags> <target>

.SH Example
.B
cate
static -f

.SH Flags (or options)
.TP
.BR \-tN
Sets thread-count to 
.B
N

.TP
.BR \-iV
Init a project with the name
.B
V

.TP
.BR \-l
Lists Catefiles in Catefiles directory (set by Catel).

.TP
.BR \-y
Install without asking. (always answer 'y')

.TP
.BR \-n
Don't install. (always answer 'n')

.TP
.BR \-f
Forcefully rebuilds.

.TP
.BR \-D
Disables all script-defined 
.B
system()
calls in script

.TP
.BR \-d
Print all commands in script without running them. (dry run)

.TP
.BR \-S
Smolize even if not defined in script.

.TP
.BR \-h
Shows help (with pretty colors).

.TP
.BR \-v
Shows version

.SH Credits

.TP
.BR Yogurt:
Creator and maintainer of Cate.

.TP
.BR Lemon:
Creator and maintainer of Cate.